In [1]:
import psycopg2
import numpy as np
import psycopg2.extras as extras
import pandas as pd
import pickle
from preprocessor import preprocessor

In [2]:
def load_pkl(pkl_file):
    with open(pkl_file, 'rb') as inp:
        pickled_obj = pickle.load(inp)
    return pickled_obj

In [3]:
pre = load_pkl("../data-processing/processed_data/train_data/pre.pkl")

In [4]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng

In [4]:
import psycopg2
import numpy as np
import psycopg2.extras as extras
import pandas as pd
  
  
def execute_values(conn, df, table):
  
    tuples = [tuple(x) for x in df.to_numpy()]
  
    cols = ','.join(list(df.columns))
    # SQL query to execute
    query = "INSERT INTO %s(%s) VALUES %%s" % (table, cols)
    cursor = conn.cursor()
    try:
        extras.execute_values(cursor, query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("the dataframe is inserted")
    cursor.close()

In [5]:
hostname = 'localhost'
username = 'ravi'
password = 'techprixa1234' # your password
database = 'news_recommendation_dev'
connection = psycopg2.connect(host=hostname, user=username, password=password, dbname=database)

In [8]:
pre.df.columns

Index(['user', 'url', 'additional_images', 'content', 'date', 'head_image',
       'heading', 'label', 'source', 'author', 'author_img', 'all_content',
       'all_heading_content_list', 'all_heading_content', 'keywords',
       'Dominant_Topic', 'final_rating', 'user_index', 'url_index',
       'label_index', 'article_id'],
      dtype='object')

In [10]:
dir(pre)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'df',
 'get_keyword_label',
 'get_user_url_label_embedding',
 'index_label_mapping',
 'index_url_mapping',
 'index_user_mapping',
 'keyword_enocder',
 'keyword_to_label_enocder',
 'keyword_to_url_dict',
 'keywords_list',
 'label_ecoder',
 'label_index_mapping',
 'url_and_label_df',
 'url_emb_sizes',
 'url_embedding_cardinality',
 'url_flds',
 'url_index_mapping',
 'url_to_index_and_labels_dict',
 'url_to_keyword_and_labels_dict',
 'url_to_keyword_dict',
 'user_df',
 'user_emb_sizes',
 'user_embedding_cardinality',
 'user_flds',
 'user_index_mapping',
 'y']

In [12]:
pre.keyword_to_url_dict

{'[13073, 27456, 12617, 6083, 31465, 19698, 12934, 22223, 25310, 3877, 220, 23679, 36243, 34199, 15598, 124, 28786, 17785, 19745, 38483]': 31665,
 '[5968, 30411, 14608, 14843, 9248, 1574, 8248, 29751, 32524, 11920, 18917, 4735, 13866, 12599, 27748, 8380, 10371, 6078, 31286, 16181]': 31538,
 '[27982, 34743, 30577, 20802, 28810, 27104, 25394, 21903, 17647, 5977, 8885, 12453, 15553, 28706, 35005, 10408, 577, 23822, 3852, 14539]': 31547,
 '[11916, 31053, 32043, 21744, 8895, 162, 10331, 5786, 14512, 14053, 5390, 12874, 24741, 2244, 13522, 35967, 27436, 13659, 5016, 9071]': 31549,
 '[36721, 14183, 36254, 15011, 18182, 5073, 6950, 33083, 14975, 22379, 23595, 29349, 18760, 37628, 9820, 23414, 34528, 31840, 35366, 29054]': 31529,
 '[27125, 7269, 14972, 30048, 34698, 31974, 19501, 31786, 4809, 31634, 21144, 33594, 27366, 26194, 8158, 27501, 32339, 31693, 13088, 20377]': 31546,
 '[12854, 6950, 25804, 18258, 15011, 11854, 2456, 2974, 35610, 36329, 1914, 37283, 6670, 7858, 31373, 19366, 34, 24815, 36045, 10634]': 31543,
 '[32893, 23838, 11801, 6304, 16999, 3001, 23107, 25442, 28575, 7357, 20908, 7115, 28588, 30429, 11008, 38407, 36002, 20913, 2408, 28949]': 31541,
 '[21508, 14020, 21426, 24096, 21017, 26342, 33261, 15276, 5606, 12404, 17790, 30762, 19077, 5620, 34395, 7988, 15011, 31827, 31044, 21876]': 31533,
 '[33449, 10828, 36923, 11809, 6950, 15957, 31645, 3691, 10919, 12382, 5849, 21924, 21047, 9336, 37091, 31542, 15011, 5405, 29749, 19284]': 31065,
 '[23297, 21529, 10360, 19024, 31257, 9972, 11071, 7103, 30848, 33722, 3894, 15104, 14655, 4029, 22517, 12769, 3290, 31102, 34619, 29404]': 31539,
 '[38924, 18033, 28314, 36634, 26087, 37084, 28297, 12328, 11881, 4920, 37869, 18247, 6428, 15409, 24525, 11111, 20447, 25928, 22533, 8655]': 31556,
 '[34886, 36887, 5073, 1259, 16268, 23262, 19145, 7988, 5402, 7812, 23460, 31112, 22035, 13073, 23718, 33389, 11970, 17575, 30714, 12976]': 31526,
 '[10290, 11101, 3575, 1971, 1169, 34528, 18576, 14020, 12934, 26045, 8996, 8942, 8655, 3693, 17571, 31912, 16089, 1819, 30392, 22999]': 31551,
 '[33845, 9030, 37664, 30336, 32567, 24787, 2712, 22060, 38510, 3062, 4319, 9590, 5843, 35001, 25007, 10149, 33458, 33632, 18306, 30981]': 31535,
 '[22500, 14965, 35403, 35474, 18217, 36066, 8559, 28035, 2484, 7416, 18062, 17499, 12454, 6981, 6950, 23316, 17835, 23572, 16077, 4097]': 31557,
 '[38276, 12328, 22481, 26156, 15892, 20547, 35593, 31986, 22777, 27634, 38363, 14009, 20224, 38548, 19203, 20047, 19164, 30675, 15987, 2442]': 31558,
 '[13517, 24022, 3100, 35837, 37179, 5769, 13522, 9353, 31650, 22280, 18395, 4265, 35364, 15878, 17830, 9700, 11363, 20534, 13633, 34212]': 31555,
 '[22174, 11583, 1848, 34001, 4168, 22195, 2100, 19177, 12362, 23229, 20563, 8517, 30335, 34619, 734, 10970, 17245, 1259, 33449, 14991]': 31525,
 '[26574, 37674, 17504, 32198, 17988, 4383, 22464, 10568, 7269, 24816, 6765, 33066, 21099, 3850, 38697, 38954, 9316, 10365, 33737, 6245]': 31481,
 '[39158, 17589, 38483, 17252, 2624, 30798, 19203, 31552, 38910, 24717, 34229, 13858, 30778, 37997, 31722, 279, 14009, 13317, 13718, 18559]': 31540,
 '[6682, 4892, 7555, 31000, 3665, 19949, 5105, 35797, 11067, 9110, 13146, 3672, 29515, 30815, 27979, 12599, 17537, 16452, 34181, 20093]': 31548,
 '[26832, 22190, 6389, 16730, 7110, 16138, 9353, 37066, 10728, 3431, 21500, 4396, 15346, 11363, 12352, 18091, 2352, 29990, 23563, 28025]': 31527,
 '[18738, 35343, 13874, 33389, 12992, 23188, 21426, 12324, 3980, 465, 6245, 1814, 23943, 24433, 22777, 4708, 31986, 15552, 28786, 31012]': 31565,
 '[36438, 23813, 13477, 27214, 3531, 7233, 32646, 7061, 28653, 7106, 37906, 4168, 21071, 1229, 37060, 18894, 37084, 25466, 207, 4864]': 31544,
 '[29521, 14183, 20015, 5092, 5073, 4923, 14442, 9160, 38510, 30660, 21371, 14964, 35637, 7558, 6950, 10536, 37194, 12676, 12883, 6032]': 31564,
 '[24991, 37121, 26049, 6142, 6950, 30928, 4834, 18840, 37863, 12854, 32227, 12426, 10349, 16195, 5964, 7293, 11522, 8956, 28172, 24954]': 31489,
 '[25656, 32689, 1308, 21419, 8901, 26497, 1043, 25582, 9061, 7405, 8239, 37548, 36546, 4500, 3379, 32532, 12362, 2351, 9550, 13868]': 31560,
 '[37084, 27982, 13934, 4652, 17090, 19722, 19919, 24223, 1725, 22337, 27573, 23318, 5769, 29349, 35693, 13890, 34413, 5519, 21047, 22949]': 31561,
 '[9724, 12295, 18738, 16299, 18788, 17922, 27400, 35343, 17103, 12992, 4796, 5873, 3880, 14150, 38227, 33991, 4315, 734, 2279, 5405]': 31563,
 '[22427, 31399, 20194, 17826, 23516, 14724, 25596, 33638, 28510, 9282, 20903, 9195, 1022, 6422, 21089, 23813, 13584, 20742, 39127, 25241]': 31567,
 '[15011, 25093, 37351, 10828, 20679, 33762, 33043, 27946, 19696, 551, 1606, 28126, 7075, 28578, 18264, 25469, 20601, 9661, 2779, 2140]': 31512,
 '[15137, 24741, 22174, 11916, 20772, 32647, 10349, 21925, 16292, 35967, 37310, 1259, 11583, 21931, 30575, 5394, 21646, 32255, 8452, 21254]': 31569,
 '[33715, 7269, 16906, 11363, 35627, 1566, 1236, 19471, 10956, 8707, 38607, 13242, 25599, 22427, 14068, 34497, 13584, 32922, 11916, 8904]': 31500,
 '[28314, 7511, 18709, 37354, 1405, 14935, 25720, 4633, 9466, 26847, 36067, 32297, 38908, 20890, 24148, 9935, 28969, 28549, 32968, 33481]': 31559,
 '[12803, 31000, 13522, 5510, 37523, 6682, 231, 19200, 37671, 2926, 32922, 20889, 21475, 36967, 32412, 34182, 13150, 33186, 29581, 10566]': 31507,
 '[8697, 38483, 35182, 23489, 1435, 8942, 18250, 27982, 37777, 23254, 22600, 4289, 38299, 37846, 11118, 18500, 1169, 11101, 32060, 37667]': 31571,
 '[18738, 20173, 6422, 10334, 30796, 33449, 21426, 35343, 13150, 31012, 22200, 25093, 32213, 27884, 16076, 576, 25310, 12295, 463, 23997]': 31566,
 '[7501, 32922, 22464, 14843, 9122, 25695, 21529, 38404, 23158, 38289, 6682, 10349, 31116, 19206, 30689, 35668, 29292, 17793, 10568, 39019]': 31495,
 '[5908, 10753, 19152, 16075, 17792, 1914, 24295, 23869, 15540, 23621, 607, 33695, 14876, 13150, 31298, 10568, 3691, 10117, 29416, 34359]': 31470,
 '[37173, 21731, 31511, 12112, 21507, 202, 12992, 37572, 23792, 37937, 1081, 35868, 19628, 833, 24625, 10118, 8450, 28423, 12054, 28941]': 31524,
 '[19388, 27953, 27021, 17927, 12072, 18760, 27214, 17877, 16184, 18207, 30663, 14636, 279, 21266, 21635, 21973, 6426, 19886, 13914, 36745]': 31508,
 '[14346, 30714, 31832, 10541, 10023, 15192, 2681, 27139, 31985, 19757, 26797, 14501, 11431, 7922, 24088, 4070, 9764, 32840, 31476, 31800]': 31506,
 '[264, 5293, 7806, 36072, 7269, 25725, 33837, 22373, 32567, 5270, 13028, 38675, 14724, 124, 13633, 9231, 7037, 13489, 5927, 6414]': 31006,
 '[22032, 31756, 2845, 11573, 6457, 25694, 20066, 10398, 34882, 4147, 15957, 31152, 529, 31728, 15153, 38147, 21976, 12072, 14636, 27638]': 31545,
 '[26337, 13522, 7619, 30751, 31175, 1259, 14020, 21744, 19745, 32700, 5673, 21713, 396, 8175, 16752, 15554, 23739, 1910, 11118, 1158]': 31502,
 '[23929, 18022, 14231, 11067, 36658, 23869, 12112, 16181, 29751, 19471, 19700, 30815, 11250, 23696, 10097, 16798, 25367, 7621, 13435, 22123]': 31552,
 '[35474, 36066, 36704, 5049, 18033, 38111, 28709, 33636, 31895, 37073, 32558, 17499, 25442, 31188, 14609, 18198, 7511, 33625, 41, 14688]': 31574,
 '[13517, 3100, 33631, 13522, 9353, 24022, 26268, 26601, 9029, 33695, 11363, 18009, 12192, 5769, 2756, 36967, 31031, 2488, 35640, 37060]': 31575,
 '[30154, 7465, 26084, 22399, 13702, 14823, 3033, 35185, 21976, 38908, 36464, 28663, 24214, 17987, 12240, 24906, 24770, 29772, 14822, 20903]': 31573,
 '[8758, 31150, 21566, 29425, 14576, 18707, 22688, 78, 12295, 19314, 17972, 35486, 16756, 2974, 18109, 34619, 22161, 5402, 20640, 24912]': 31576,
 '[3485, 8775, 25015, 28314, 13477, 37771, 8987, 31286, 5033, 20631, 12384, 26703, 4822, 9238, 5716, 38138, 2528, 39017, 34182, 5513]': 31578,
 '[18524, 17300, 13095, 29761, 12998, 34093, 3907, 9061, 28873, 24478, 9697, 21898, 27183, 11057, 14220, 22133, 31632, 25032, 22010, 29487]': 31458,
 '[20598, 17647, 3919, 29331, 37529, 8542, 37997, 27456, 2165, 2779, 1695, 35346, 23973, 16086, 2725, 3501, 14964, 33938, 18151, 4049]': 31577,
 '[32412, 28265, 32610, 2236, 16076, 35135, 29679, 33695, 5395, 26121, 18097, 4581, 20784, 26409, 17512, 18814, 5742, 25394, 20543, 12076]': 31579,
 '[9504, 36634, 13382, 6727, 38001, 23973, 5673, 11407, 21430, 31265, 30184, 14927, 14009, 3185, 34188, 23489, 37529, 1617, 35550, 5961]': 31580,
 '[1397, 13146, 4566, 34182, 9108, 12336, 17300, 34214, 20441, 36053, 15957, 8305, 8057, 34244, 21971, 17414, 34227, 23973, 4515, 31728]': 31523,
 '[19943, 19778, 23074, 16292, 6950, 21501, 25533, 5252, 6022, 15011, 7724, 39119, 7374, 18523, 19938, 10990, 36923, 11601, 4216, 1888]': 31581,
 '[2435, 9551, 23243, 15892, 32841, 37173, 15395, 18894, 38650, 26156, 34882, 649, 10568, 36772, 22818, 16223, 19745, 28187, 23158, 38139]': 31583,
 '[24582, 19089, 16503, 19700, 7279, 17593, 32922, 9851, 33695, 27884, 124, 20936, 23368, 11654, 9143, 5924, 6174, 25637, 9003, 13899]': 31192,
 '[21743, 15703, 36853, 37955, 27949, 33268, 37904, 21430, 23297, 1531, 25655, 5948, 30269, 37102, 6682, 19991, 7488, 29686, 22233, 38339]': 31542,
 '[28935, 35263, 35797, 35183, 28256, 3603, 38728, 25442, 23214, 23838, 22332, 12362, 26868, 5053, 20284, 15420, 4583, 37712, 20832, 2705]': 31584,
 '[20679, 27982, 5092, 16060, 1695, 10536, 1725, 19402, 29839, 1475, 34117, 8722, 19243, 28992, 15011, 29683, 19297, 8396, 37628, 6442]': 31570,
 '[33845, 6022, 10318, 10300, 9030, 11715, 36399, 1634, 13408, 9282, 13075, 463, 28640, 33458, 11117, 37434, 37084, 743, 34053, 3185]': 31473,
 '[11488, 21647, 37139, 24912, 1516, 1931, 22945, 12124, 14388, 15737, 32746, 13010, 18894, 28367, 12031, 33976, 11008, 25442, 35483, 489]': 31592,
 '[23225, 401, 32893, 11021, 18160, 4686, 6524, 30961, 23838, 15137, 35265, 5170, 6299, 10127, 28434, 36704, 12362, 6304, 2408, 2100]': 31589,
 '[7170, 20078, 22716, 19369, 14608, 34765, 23673, 10059, 10349, 32672, 10568, 16525, 28258, 30383, 17845, 11316, 21098, 38277, 19594, 21783]': 31476,
 '[28653, 33223, 24072, 19038, 11314, 33596, 29712, 15127, 5651, 4168, 25637, 5769, 9677, 22600, 25951, 31357, 1365, 1396, 16396, 35344]': 31478,
 '[38910, 17589, 38483, 17252, 20078, 2624, 35177, 13858, 30798, 31552, 24717, 34229, 37997, 16882, 39158, 31722, 478, 14009, 2301, 13317]': 31593,
 '[20207, 16614, 21501, 25093, 25394, 6838, 3572, 30751, 9962, 30943, 3201, 31895, 33072, 9398, 37644, 27641, 32646, 26722, 35540, 30981]': 31596,
 '[17274, 22174, 13094, 3701, 31118, 3792, 36583, 35475, 32570, 3139, 27510, 12409, 20807, 15728, 24398, 19044, 25394, 39116, 16113, 12112]': 31464,
 '[12318, 37519, 34999, 31160, 21430, 37270, 22645, 12287, 30920, 27002, 4227, 9407, 4908, 35291, 7180, 28797, 37106, 15464, 13958, 25278]': 31598,
 '[32683, 345, 18765, 33670, 2967, 21903, 9724, 8182, 16059, 11828, 18109, 33695, 5090, 3914, 11710, 13170, 2431, 38272, 9201, 18230]': 31503,
 '[8942, 24008, 22174, 28449, 37362, 34053, 7832, 23537, 20089, 20047, 14009, 12112, 31118, 17972, 11067, 18199, 22872, 24398, 7267, 38335]': 31595,
 '[3747, 162, 24871, 15011, 32060, 16643, 458, 6950, 34, 9487, 17265, 3076, 37664, 3681, 31491, 38733, 34203, 15401, 5064, 8276]': 31590,
 '[35593, 20483, 29472, 23838, 528, 29433, 1848, 18894, 10472, 5888, 2859, 14540, 22174, 38898, 30778, 20176, 12813, 22285, 34556, 25803]': 31572,
 '[21198, 15449, 13718, 3969, 11498, 33458, 11879, 28432, 16202, 34586, 30490, 36926, 14363, 16787, 31414, 33638, 20209, 33751, 2442, 37925]': 31591,
 '[38852, 21529, 19160, 7652, 74, 20086, 34395, 13943, 37600, 37084, 5067, 35511, 25758, 12825, 28501, 3185, 21967, 31175, 30490, 30352]': 31605,
 '[3531, 19783, 7682, 15435, 22174, 30308, 7106, 31511, 9353, 23332, 16374, 18395, 31188, 36634, 32914, 576, 33562, 24510, 13423, 32562]': 31606,
 '[20602, 13088, 31794, 22494, 17918, 28957, 12934, 29899, 12328, 28786, 9185, 279, 4857, 27680, 29529, 23943, 1634, 463, 14928, 567]': 31604,
 '[1004, 17335, 27267, 6457, 11916, 12826, 17828, 20300, 1298, 14635, 27863, 33371, 31407, 5037, 35696, 8517, 5786, 35610, 28652, 28256]': 31610,
 '[34960, 223, 11204, 23195, 26260, 26555, 22010, 25156, 37628, 29773, 22281, 1842, 23806, 17491, 1985, 21161, 27436, 38447, 25574, 23739]': 31608,
 '[6878, 2605, 7216, 37025, 23172, 7898, 1809, 34307, 17785, 32641, 30866, 445, 22399, 2779, 8886, 17116, 29529, 5233, 39082, 31965]': 31562,
 '[37511, 13522, 1480, 17785, 5804, 38845, 38375, 27080, 20890, 22988, 2816, 5049, 18746, 35194, 20908, 28342, 33696, 13866, 14991, 9106]': 31568,
 '[9504, 11407, 31986, 30866, 35537, 23943, 8182, 18685, 5080, 1695, 6727, 15957, 21474, 36684, 125, 36634, 38939, 7518, 38698, 15449]': 31618,
 '[10472, 29472, 25496, 15031, 27964, 5394, 15599, 11613, 11571, 17915, 18099, 11852, 8718, 30751, 32317, 5090, 20988, 24022, 1745, 24149]': 31616,
 '[20180, 24582, 14183, 31537, 38675, 29048, 18020, 24737, 30482, 8246, 2656, 35451, 11067, 33389, 14724, 31992, 37307, 36936, 28267, 5777]': 31600,
 '[34743, 27214, 6654, 27982, 303, 30572, 33470, 30584, 8182, 33389, 28256, 25093, 25394, 7465, 463, 1879, 16932, 23710, 20657, 24398]': 31613,
 '[27328, 13794, 18345, 14605, 4917, 2779, 29048, 38704, 34001, 6537, 22937, 35621, 32082, 36704, 28915, 6513, 7531, 11535, 17187, 36726]': 31519,
 '[38706, 38447, 21287, 15297, 2625, 10218, 8161, 15011, 11118, 25335, 2133, 12322, 10104, 9170, 14367, 30104, 19468, 7544, 2779, 19920]': 31597,
 '[35611, 23147, 37861, 38649, 11916, 26493, 7248, 25411, 20002, 15691, 23869, 25652, 9551, 11470, 33697, 5703, 1725, 10855, 8996, 35706]': 31617,
 '[37610, 3062, 19920, 5728, 31077, 17878, 30533, 37084, 17499, 2279, 12677, 30666, 27436, 25310, 21501, 286, 29048, 23739, 38483, 1374]': 31594,
 '[8182, 4391, 19158, 38001, 7775, 23782, 23554, 529, 22661, 17070, 31965, 31190, 21474, 23710, 18161, 3529, 31630, 27400, 29301, 2725]': 31599,
 '[10308, 32412, 11761, 18396, 36589, 29749, 37331, 27214, 2209, 3925, 23869, 27713, 36526, 32763, 10642, 24850, 4556, 24535, 9943, 29799]': 31622,
 '[24359, 20441, 1993, 32373, 16505, 10857, 21266, 31728, 23739, 33773, 3843, 18710, 6094, 25512, 34227, 35417, 23262, 36328, 4515, 1581]': 31601,
 '[37434, 8048, 14102, 28941, 28035, 37855, 34053, 14086, 29529, 16752, 13475, 12222, 10892, 18866, 35586, 27100, 37084, 31175, 19963, 18830]': 31614,
 '[12975, 31611, 21120, 21426, 38419, 33458, 4501, 12253, 33601, 33845, 32941, 38619, 38172, 16202, 18695, 16076, 28501, 11715, 9030, 38302]': 31623,
 '[17785, 31077, 30563, 2383, 16076, 13075, 32941, 28786, 16405, 10503, 38483, 38458, 15573, 21120, 34407, 25540, 9943, 27436, 13150, 23739]': 31625,
 '[17785, 19608, 4525, 9804, 37056, 21120, 1809, 16405, 12975, 31175, 15733, 31611, 6776, 17965, 13506, 13073, 2974, 28786, 5668, 21426]': 31626,
 '[5968, 23387, 33437, 30490, 38813, 14334, 4208, 34146, 10378, 38623, 10437, 31237, 16195, 24339, 24816, 27275, 2870, 8053, 17397, 31806]': 30871,
 '[17261, 29718, 23838, 13155, 1274, 9810, 29093, 8966, 6950, 21254, 29433, 23718, 15303, 6866, 17357, 4030, 23551, 6288, 11546, 28256]': 31627,
 '[11021, 16837, 32670, 25394, 31321, 31062, 23838, 9724, 27214, 34182, 33481, 38483, 13242, 23729, 7465, 20640, 16113, 7285, 34359, 35165]': 31620,
 '[6423, 12051, 33278, 20767, 11021, 31118, 11143, 5405, 1259, 24398, 31986, 13472, 14169, 15137, 23139, 6047, 15394, 22174, 33407, 11088]': 31612,
 '[14993, 5904, 11774, 15011, 2138, 38150, 17647, 6882, 6950, 36932, 15964, 12295, 36692, 32559, 26250, 6691, 7858, 13328, 22949, 19386]': 31603,
 '[17767, 17785, 34774, 5026, 27490, 21878, 6776, 35521, 15164, 28862, 16076, 15733, 28501, 13506, 35640, 2974, 21120, 27656, 5668, 20908]': 31624,
 '[12362, 25546, 649, 11008, 3603, 10774, 37359, 5716, 3749, 7115, 36704, 977, 19575, 24029, 7822, 22429, 15928, 908, 30247, 4425]': 31602,
 '[9169, 33449, 16756, 8655, 20679, 19016, 9122, 13150, 35950, 34407, 22781, 21146, 8182, 5394, 5099, 30913, 27408, 28653, 33891, 1695]': 31333,
 '[12322, 15011, 23311, 17512, 1914, 29256, 20640, 7988, 4549, 11259, 34451, 37664, 17683, 2541, 9962, 24323, 36585, 12363, 14377, 11951]': 31628,
 '[22427, 31053, 30943, 478, 31968, 11916, 949, 966, 35143, 15373, 33300, 7171, 28287, 16160, 8470, 807, 5786, 13633, 6586, 5964]': 31494,
 '[24991, 37664, 1914, 13633, 23869, 24402, 27748, 34978, 26105, 30273, 28465, 28015, 29299, 10149, 33774, 22464, 1916, 1612, 35165, 22905]': 31504,
 '[29227, 32670, 23838, 27214, 17399, 24398, 28652, 28606, 3151, 25394, 16837, 13242, 1858, 24260, 10616, 16397, 28965, 31118, 25305, 15192]': 31621,
 '[2638, 29349, 34265, 37771, 29971, 484, 12431, 33901, 7775, 38697, 18507, 32567, 12176, 19636, 29990, 32532, 23673, 7465, 19745, 25928]': 31480,
 '[35967, 2580, 16947, 20772, 36488, 34634, 29444, 33375, 28890, 15137, 3381, 24778, 7876, 31667, 9541, 34023, 9070, 9233, 1858, 14404]': 31609,
 '[17785, 16076, 12975, 31611, 21426, 16982, 2974, 15733, 35521, 21120, 20033, 13580, 1962, 28786, 6798, 3062, 11349, 20044, 28862, 17767]': 31631,
 '[12362, 18750, 977, 3749, 24344, 37781, 401, 32297, 23518, 17598, 17493, 18878, 3001, 33481, 36704, 26087, 24975, 2808, 2950, 35538]': 31629,
 '[20240, 15560, 29895, 28172, 31449, 6950, 11809, 17265, 23985, 28783, 5969, 19100, 26096, 38030, 35176, 1724, 16030, 15080, 13744, 27285]': 31630,
 '[33449, 35343, 21248, 8881, 29433, 31062, 22005, 13826, 23838, 20021, 6423, 15137, 401, 16076, 7465, 12295, 10052, 23997, 29012, 3356]': 31619,
 '[25442, 35474, 12362, 37300, 7064, 23838, 463, 16302, 12031, 32236, 5135, 27214, 34093, 22332, 12997, 279, 15137, 18462, 18576, 33389]': 31615,
 '[29532, 20285, 29751, 19285, 11435, 23601, 14724, 10809, 5682, 38675, 7812, 22175, 22123, 6963, 7988, 5909, 16181, 38474, 31507, 22125]': 31518,
 '[16906, 37608, 9575, 9272, 32610, 5090, 2624, 38483, 21111, 18709, 1443, 23229, 3525, 17110, 13914, 2644, 26205, 1432, 5149, 15763]': 31278,
 '[23955, 13580, 32724, 23118, 17785, 34219, 21687, 8636, 1871, 32334, 4864, 8480, 20033, 17594, 1169, 37696, 1258, 23869, 24275, 30915]': 31636,
 '[5495, 1268, 6740, 35407, 5090, 3520, 2521, 34381, 15069, 13242, 6425, 31152, 18894, 6288, 34359, 39008, 27144, 5394, 8190, 18178]': 31634,
 '[5909, 19780, 19700, 19471, 9643, 27214, 36337, 25876, 35062, 463, 607, 9697, 19885, 529, 8559, 181, 37043, 26026, 19287, 1914]': 31055,
 '[33648, 31237, 19943, 2182, 6950, 15076, 15011, 3699, 18202, 23074, 37246, 6658, 16292, 14088, 6576, 14769, 25417, 25045, 18178, 21484]': 31639,
 '[19194, 30747, 14009, 34053, 25093, 6838, 25394, 37791, 31009, 18946, 17800, 28328, 22738, 39104, 37773, 15900, 25540, 37444, 24775, 18814]': 31632,
 '[32922, 2244, 6950, 15011, 5384, 29287, 6682, 11809, 25801, 13214, 15288, 34155, 3041, 19949, 14774, 18559, 35867, 32071, 24778, 267]': 31638,
 '[19169, 8289, 26386, 16430, 29965, 6941, 29925, 629, 15589, 11801, 6507, 3222, 33239, 3113, 24214, 31508, 17987, 27436, 2215, 28588]': 31635,
 '[3485, 7031, 15358, 38697, 13522, 10568, 3595, 8820, 7068, 22600, 19745, 27603, 33695, 4264, 24199, 16430, 9406, 7064, 11613, 37406]': 31588,
 '[7876, 16947, 33375, 37310, 1259, 8457, 22174, 15069, 5394, 16778, 23838, 1858, 11299, 34634, 24778, 16932, 24804, 31237, 24234, 15137]': 31640,
 '[36634, 6727, 16299, 9504, 3564, 15449, 20767, 12773, 5850, 4757, 37992, 23271, 31986, 19097, 39011, 31116, 317, 26799, 19332, 30666]': 31644,
 '[17321, 6950, 19366, 21325, 27396, 28920, 35403, 1914, 23696, 24003, 14170, 15456, 35867, 8297, 22950, 36288, 3536, 28834, 11045, 13434]': 31642,
 '[8942, 32317, 37872, 31583, 4289, 31321, 9764, 10391, 5394, 2723, 30950, 30212, 24058, 3122, 31062, 24732, 9957, 21712, 8182, 14434]': 31646,
 '[8942, 16062, 1259, 39082, 21426, 9801, 24955, 24471, 11122, 24398, 25865, 6416, 13779, 2978, 3409, 18102, 14207, 16294, 3892, 29825]': 31647,
 '[36454, 13409, 33670, 36178, 16756, 26550, 18767, 14823, 26832, 18094, 19471, 9889, 21956, 15666, 6471, 30287, 279, 34359, 24177, 23665]': 31648,
 '[6658, 32255, 19834, 17580, 15137, 35451, 25442, 4379, 663, 12584, 8724, 34619, 30639, 24509, 31000, 24311, 36670, 27726, 13175, 28610]': 31650,
 '[30701, 4982, 31992, 21868, 14725, 29301, 38302, 11913, 1229, 9351, 8463, 25466, 36614, 37997, 20300, 14308, 16823, 4791, 16486, 7115]': 31651,

In [16]:
pre.keyword_enocder.get(1)

'ढिस्को'

In [17]:
article_df = pre.df[['article_id','url','head_image','heading','date','content','additional_images','source','label','keywords']]

In [ ]:
views_df = article_df.pivot_table(columns=['article_id'], aggfunc='size')
views_df.get('yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8')

In [29]:
article_df['likes'] = 0
article_df['shares'] = 0
article_df['type'] = 'recommended'
article_df['views'] = article_df.apply(lambda x: views_df.get(x['article_id']), axis=1)

/tmp/ipykernel_45644/2542855077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['likes'] = 0
/tmp/ipykernel_45644/2542855077.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['shares'] = 0
/tmp/ipykernel_45644/2542855077.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['type'] = 'recommended'
/tmp/ipykernel_45644/2542855077.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['views'] = article_df.apply(lambda x: views_df.get(x['article_id']), axis=1)

In [31]:
article_df['ignores'] = 0
article_df['total_comments'] = 0
article_df['bookmarks'] = 0

/tmp/ipykernel_45644/1681522445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['ignores'] = 0
/tmp/ipykernel_45644/1681522445.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['total_comments'] = 0
/tmp/ipykernel_45644/1681522445.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['bookmarks'] = 0

In [32]:
article_df.drop_duplicates(subset=['article_id'], keep='last', inplace=True)

/tmp/ipykernel_45644/2929885987.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df.drop_duplicates(subset=['article_id'], keep='last', inplace=True)

In [34]:
article_df.rename(columns={"article_id": "id"}, inplace=True)

/home/prixa-ml/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [44]:
article_df.rename(columns={"additional_image": "additional_img"}, inplace=True)

/home/prixa-ml/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [47]:
article_df.drop('keywords', 1, inplace=True)

/home/prixa-ml/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [53]:
import ast

def str_to_list(list_string):
    return ast.literal_eval(list_string)

In [54]:
article_df['content'] = article_df['content'].apply(lambda x: str_to_list(x))

/tmp/ipykernel_45644/3092641773.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['content'] = article_df['content'].apply(lambda x: str_to_list(x))

In [57]:
article_df['additional_img'] = article_df['additional_img'].apply(lambda x: str_to_list(x))

/tmp/ipykernel_45644/3155347137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  article_df['additional_img'] = article_df['additional_img'].apply(lambda x: str_to_list(x))

In [55]:
article_df

,id,url,head_image,heading,date,content,additional_img,source,label,likes,shares,type,views,ignores,total_comments,bookmarks
10,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,[नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अम...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,0,0,recommended,11,0,0,0
11,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI,https://www.ratopati.com/story/94749,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",2076-04-07 00:00:00+05:45,[बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरने...,[],ratopati,मनोरञ्जन,0,0,recommended,1,0,0,0
13,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U,https://www.ratopati.com/story/94766,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",2076-04-07 00:00:00+05:45,[काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्टी...,[],ratopati,मुख्य समाचार,0,0,recommended,2,0,0,0
15,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk,https://www.ratopati.com/story/94769,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,2076-04-07 00:00:00+05:45,[काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाही...,[],ratopati,प्रदेश मुख्य समाचार,0,0,recommended,2,0,0,0
16,UhK8tdrfsbFHVGSSnfApmu37DePbCDPedGr2whVu2AI,https://www.ratopati.com/story/94721,https://ratopati.prixa.net/media/albums/arrest...,होटलमा अनैतिक सम्बन्ध राख्ने १० जना पक्राउ,2076-04-06 00:00:00+05:45,[बुटवल-अनैतिक सम्बन्ध राखेको आरोपमा नवलपरासीको...,[],ratopati,समाचार,0,0,recommended,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,https://www.thahakhabar.com/news/127679,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,2078-02-24 00:00:00+05:45,[ नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री केपी...,[],thahakhabar,राजनीति,0,0,recommended,1,0,0,0
707193,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,https://www.thahakhabar.com/news/127379,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,2078-02-20 00:00:00+05:45,[ नारायणहिटी राजदरबार हत्याकाण्ड छानबिनको उच्च...,[],thahakhabar,राजनीति,0,0,recommended,1,0,0,0
707194,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,https://www.thahakhabar.com/news/127900,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,2078-02-26 00:00:00+05:45,[ प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओवा...,['https://thahacdn.prixacdn.net/media/albums/%...,thahakhabar,राजनीति,0,0,recommended,1,0,0,0
707195,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,https://www.thahakhabar.com/news/127783,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,2078-02-25 00:00:00+05:45,[ कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछु...,[],thahakhabar,विश्व,0,0,recommended,1,0,0,0
707196,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,https://www.thahakhabar.com/news/127887,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",2078-02-26 00:00:00+05:45,[मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्र...,['https://thahacdn.prixacdn.net/media/albums/l...,thahakhabar,राजनीति,0,0,recommended,1,0,0,0

In [37]:
import psycopg2
import numpy as np
import psycopg2.extras as extras

In [38]:
def execute_values(conn, df, table):
  
    tuples = [tuple(x) for x in df.to_numpy()]
  
    cols = ','.join(list(df.columns))
    # SQL query to execute
    query = "INSERT INTO %s(%s) VALUES %%s" % (table, cols)
    cursor = conn.cursor()
    try:
        extras.execute_values(cursor, query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("the dataframe is inserted")
    cursor.close()

In [39]:
hostname = 'localhost'
username = 'ravi'
password = 'techprixa1234' # your password
database = 'news_recommendation_dev'
connection = psycopg2.connect(host=hostname, user=username, password=password, dbname=database)

In [58]:
execute_values(connection, article_df, 'article')

the dataframe is inserted

In [33]:
article_df

,article_id,url,head_image,heading,date,content,additional_images,source,label,keywords,likes,shares,type,views,ignores,total_comments,bookmarks
10,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11,0,0,0
11,yJC-tHpfRpKEH3En-YScXK0m8eEWOqouPijF8BonHKI,https://www.ratopati.com/story/94749,https://ratopati.prixa.net/media/albums/sushmi...,"सुस्मिता सेनलाई चुम्बन गरिरहेको भेटिए प्रेमी, ...",2076-04-07 00:00:00+05:45,['बलिउड नायिका सुष्मिता सेनको एउटा फोटो इन्टरन...,[],ratopati,मनोरञ्जन,"[5968, 30411, 14608, 14843, 9248, 1574, 8248, ...",0,0,recommended,1,0,0,0
13,PkP3AJocUXbZCOQBCOkAACEZ6TwuXPxSMHJxzZQjN5U,https://www.ratopati.com/story/94766,https://ratopati.prixa.net/media/albums/biplab...,"सरकार वार्ताको पक्षमा देखिएन, देशलाई युद्धमा ध...",2076-04-07 00:00:00+05:45,['काठमाडौं– प्रतिवन्धित नेपाल कम्युनिस्ट पार्ट...,[],ratopati,मुख्य समाचार,"[27982, 34743, 30577, 20802, 28810, 27104, 253...",0,0,recommended,2,0,0,0
15,2gafeJYipiE31yBVKVOTjGN2bCdzFUPHZ8ymiWoiIvk,https://www.ratopati.com/story/94769,https://ratopati.prixa.net/media/albums/death_...,सर्लाहीमा छुट्टाछुट्टै दुर्घटनामा दुई जनाको मृ...,2076-04-07 00:00:00+05:45,['काठमाडौं– छुट्टछुट्टै दुर्घटनामा परेर सर्लाह...,[],ratopati,प्रदेश मुख्य समाचार,"[11916, 31053, 32043, 21744, 8895, 162, 10331,...",0,0,recommended,2,0,0,0
16,UhK8tdrfsbFHVGSSnfApmu37DePbCDPedGr2whVu2AI,https://www.ratopati.com/story/94721,https://ratopati.prixa.net/media/albums/arrest...,होटलमा अनैतिक सम्बन्ध राख्ने १० जना पक्राउ,2076-04-06 00:00:00+05:45,['बुटवल-अनैतिक सम्बन्ध राखेको आरोपमा नवलपरासीक...,[],ratopati,समाचार,"[36721, 14183, 36254, 15011, 18182, 5073, 6950...",0,0,recommended,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,https://www.thahakhabar.com/news/127679,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,2078-02-24 00:00:00+05:45,['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,[],thahakhabar,राजनीति,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",0,0,recommended,1,0,0,0
707193,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,https://www.thahakhabar.com/news/127379,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,2078-02-20 00:00:00+05:45,['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,[],thahakhabar,राजनीति,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",0,0,recommended,1,0,0,0
707194,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,https://www.thahakhabar.com/news/127900,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,2078-02-26 00:00:00+05:45,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,['https://thahacdn.prixacdn.net/media/albums/%...,thahakhabar,राजनीति,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",0,0,recommended,1,0,0,0
707195,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,https://www.thahakhabar.com/news/127783,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,2078-02-25 00:00:00+05:45,[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,[],thahakhabar,विश्व,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",0,0,recommended,1,0,0,0
707196,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,https://www.thahakhabar.com/news/127887,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",2078-02-26 00:00:00+05:45,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,['https://thahacdn.prixacdn.net/media/albums/l...,thahakhabar,राजनीति,"[22063, 36454, 30803, 16513, 38632, 21903, 509...",0,0,recommended,1,0,0,0

In [30]:
article_df

,article_id,url,head_image,heading,date,content,additional_images,source,label,keywords,likes,shares,type,views
0,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11
1,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11
2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11
3,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11
4,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,https://www.ratopati.com/story/94744,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,2076-04-07 00:00:00+05:45,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,['https://ratopati.prixa.net/media/albums/666_...,ratopati,अर्थ,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",0,0,recommended,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,https://www.thahakhabar.com/news/127679,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,2078-02-24 00:00:00+05:45,['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,[],thahakhabar,राजनीति,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",0,0,recommended,1
707193,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,https://www.thahakhabar.com/news/127379,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,2078-02-20 00:00:00+05:45,['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,[],thahakhabar,राजनीति,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",0,0,recommended,1
707194,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,https://www.thahakhabar.com/news/127900,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,2078-02-26 00:00:00+05:45,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,['https://thahacdn.prixacdn.net/media/albums/%...,thahakhabar,राजनीति,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",0,0,recommended,1
707195,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,https://www.thahakhabar.com/news/127783,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,2078-02-25 00:00:00+05:45,[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,[],thahakhabar,विश्व,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",0,0,recommended,1
707196,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,https://www.thahakhabar.com/news/127887,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",2078-02-26 00:00:00+05:45,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,['https://thahacdn.prixacdn.net/media/albums/l...,thahakhabar,राजनीति,"[22063, 36454, 30803, 16513, 38632, 21903, 509...",0,0,recommended,1

In [6]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_content,all_heading_content_list,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,"['यस्तो', 'विनिमयदरः', 'अमेरि', 'कतारी', 'रिया...",यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै ! ...,"['खनाल-नेपाल', 'समूह', 'नेता', 'सरकार', 'सहभाग...",खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,"['बाबुरामप्रति', 'लिङ्देन', 'कटाक्ष', 'आखिर', ...",बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै ...,"['प्रदेश', 'कांग्रेस', 'माओवा', 'सरकार', 'प्रद...",प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश कोरो...,"['कोरोना', 'संक्रमण', 'उच्च', 'विश्व', 'कोरोना...",कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...","['सुदूरपश्चिम', 'रावल', 'शक्ति,', 'पक्ष', 'पटक...","सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng

In [ ]:
df.drop_duplicates(keep='last')