In [1]:
import pandas as pd
import numpy as np
import pickle
from preprocessor import preprocessor
from config import pathconfig

In [2]:
def load_pkl(pkl_file):
    with open(pkl_file, 'rb') as inp:
        print(f"loading pickle file: {pkl_file}")
        pickled_obj = pickle.load(inp)
    return pickled_obj

In [4]:
if pathconfig.PRE_PKL_PATH.is_file():
    print('Loading PKL file...')
    pre = load_pkl(pathconfig.PRE_PKL_PATH)
    print('Successfully Loaded Pickle file')
else:
    print("NO PICKLE FILE FOUND SAD :(")

Loading PKL file...
loading pickle file: /home/prixa-ml/Desktop/projects/recommendation_news_api/repository/data-processing/processed_data/train_data/pre.pkl
Successfully Loaded Pickle file

In [5]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],['\xa0नारायणहिटी\xa0राजदरबार हत्याकाण्ड छानबिन...,2078-02-20 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/lin...,बाबुरामप्रति लिङ्देनको कटाक्ष : आखिर तपाईं पनि...,राजनीति,thahakhabar,थाहा संवाददाता,...,बाबुरामप्रति लिङ्देन कटाक्ष आखिर तपाईं भ्रम हु...,"[16882, 1054, 9122, 19730, 3681, 3468, 11067, ...",7,2.867965,106936,35670,22,6nSvygMbRne5PKsyXX4INkUFrqg1x4x4-Nuy2kDZU40,"[ज्ञानेन्द्र, भ्रम, राजा, अन्याय, भट्टराई, कटा...",ज्ञानेन्द्र भ्रम राजा अन्याय भट्टराई कटाक्ष तप...
707194,e8597e5ad66917ac69d457afe7b1d16c,https://www.thahakhabar.com/news/127900,['https://thahacdn.prixacdn.net/media/albums/%...,[' प्रदेश न. २ मा नेपाली कांग्रेस र नेकपा माओव...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/2_b...,प्रदेश २ मा कांग्रेस र माओवादी सरकारमा जाँदै,राजनीति,thahakhabar,थाहा संवाददाता,...,प्रदेश कांग्रेस माओवा सरकार प्रदेश नेपाली कांग...,"[21566, 1695, 19919, 15626, 31782, 35366, 5394...",2,2.880952,168174,35683,22,yvmmMilLnHHk6fZO74ldQkMVtVRllVMBauVoGLRzBz8,"[बजार, एसिड, प्रहार, युवती, भट्ट, राजधानी, स्व...",कांग्रेस माओवा मन्त्रालय रामसरोज ओमप्रकाश वीरे...
707195,433f43b6a40299d0a8c70351a2b57324,https://www.thahakhabar.com/news/127783,[],[' कोरोना संक्रमणबाट विश्वको कुनै पनि मुलुक अछ...,2078-02-25 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/cor...,कोरोना संक्रमण उच्च रहेका विश्वका १० देश,विश्व,thahakhabar,थाहा संवाददाता,...,कोरोना संक्रमण उच्च विश्व कोरोना संक्रमणबाट वि...,"[37084, 2779, 21300, 22945, 10992, 29365, 2785...",9,2.878788,48913,35681,28,bGoPy2Oe3hitvVKP6c8OYKH-7BLBDfhiNMm90qT3JHA,"[हजार, करोड, रसिया,, विश्व, कोरोना, ब्राजिल,, ...","हजार करोड रसिया, विश्व कोरोना ब्राजिल, इटाली, ..."
707196,72afa487553978646c986b80c6970d80,https://www.thahakhabar.com/news/127887,['https://thahacdn.prixacdn.net/media/albums/l...,['मंगलबार सुदूरपश्चिम प्रदेशका मुख्यमन्त्री त्...,2078-02-26 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/bhi...,"सुदूरपश्चिममा भीम रावलको शक्ति, ओली पक्ष पटक–प...",राजनीति,thahakhabar,टेकसिंह​ धामी,...,"सुदूरपश्चिम रावल शक्ति, पक्ष पटक–पटक असफल मंगल...","[22063, 36454, 30803, 16513, 38632, 21903, 509...",11,2.880952,83319,35682,22,ujy8-UV0-DZoa3Lmx2qNZyOqEt754_4YkibDzKvadng,"[सुदूरपश्चिम, भट्ट, लेखराज, प्रदेशसभा, एमाल, प...",सुदूरपश्चिम भट्ट लेखराज प्रदेशसभा एमाल पक्ष प्...

In [6]:
user_article_df = pre.df.groupby(['user','article_id']).size().reset_index(name='counts')

In [7]:
user_article_df

,user,article_id,counts
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1
...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1
490294,ffffff2559629ae1ae4d161a24e2cdbe,j7TmK1MbKkSXFCHziob7twikTt9n84mRBfzVWaxF8JA,1

In [8]:
data = user_article_df.dropna()
data = data.copy()

In [9]:
data.rename(columns={"article_id": "article", "counts": "views"},inplace=True)

In [10]:
data

,user,article,views
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1
...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1
490294,ffffff2559629ae1ae4d161a24e2cdbe,j7TmK1MbKkSXFCHziob7twikTt9n84mRBfzVWaxF8JA,1

In [11]:
# Create a numeric user_id and article_id column
data['user'] = data['user'].astype("category")
data['article'] = data['article'].astype("category")
data['user_id'] = data['user'].cat.codes
data['article_id'] = data['article'].cat.codes

In [12]:
len(data['article'].unique()), len(data['article_id'].unique())

(38054, 38054)

In [13]:
len(data['user'].unique()), len(data['user_id'].unique())

(185317, 185317)

In [14]:
data

,user,article,views,user_id,article_id
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4,0,570
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1,1,1041
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1,1,16532
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1,2,10504
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1,2,10911
...,...,...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1,185312,3849
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1,185313,26484
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1,185314,2781
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1,185315,7298
490294,ffffff2559629ae1ae4d161a24e2cdbe,j7TmK1MbKkSXFCHziob7twikTt9n84mRBfzVWaxF8JA,1,185316,27925

In [15]:
import scipy.sparse as sparse
from scipy.sparse.linalg import spsolve
import random
from sklearn.preprocessing import MinMaxScaler

In [16]:
# The implicit library expects data as a item-user matrix so we
# create two matricies, one for fitting the model (item-user) 
# and one for recommendations (user-item)
sparse_item_user = sparse.csr_matrix((data['views'].astype(float), (data['article_id'], data['user_id'])))
# sparse_user_item = sparse.csr_matrix((data['views'].astype(float), (data['user_id'], data['article_id'])))

In [17]:
from implicit.nearest_neighbours import bm25_weight
sparse_user_item = sparse_item_user.T.tocsr()

In [18]:
sparse_item_user,sparse_user_item

(<38054x185317 sparse matrix of type '<class 'numpy.float64'>'
 	with 490295 stored elements in Compressed Sparse Row format>,
 <185317x38054 sparse matrix of type '<class 'numpy.float64'>'
 	with 490295 stored elements in Compressed Sparse Row format>)

In [19]:
from implicit.als import AlternatingLeastSquares

model = AlternatingLeastSquares(factors=64, regularization=0.05)
model.fit(2 * sparse_user_item)

  0%|          | 0/15 [00:00<?, ?it/s]

In [31]:
user_id_dict = pd.Series(data.user_id.values, index=data.user).to_dict()
user_id_dict

{'00003762db942cabd188b2984897e5c5': 0,
 '00005513d5d145d61be64de14ab4b56e': 1,
 '0002eabd63d3cde55b2c77f2dcaa6ce0': 2,
 '000319e51abbb8b7845aa9458a76a008': 3,
 '0003b1b5cc4f651143a263fc1ad72f65': 4,
 '0003d0b819f28410136a64f9e4737211': 5,
 '000419ff83e2c85b965664051c2e0407': 6,
 '00048e6368b0ae8148361fa73a3a7ec7': 7,
 '0004b6c117d624c8568555355800395c': 8,
 '0005d54e85dfbb09fae7c60d6c6d2e97': 9,
 '0005d9b1e772a8e2157e23c4021dc406': 10,
 '0005f0af3015fd96528c2ac114d6268a': 11,
 '00060ec9ad3cdf33b917a16ed2025f95': 12,
 '00066712f0816e665ff5802594966fad': 13,
 '000675d8f62da0ed6608f9bd20cbc17e': 14,
 '0006b43202ab780dc35651ad251372c6': 15,
 '0006be6c307a219c99a098a1cbe742f2': 16,
 '000704e7c396dfdbeba05fdc7a4d9b24': 17,
 '0007872047ce09c541c71deb047d1fb1': 18,
 '0007d2b364bd119f1a541ed0ff1a2025': 19,
 '000832d61b2563a12ea9403e478aa769': 20,
 '000891a8f8b71bd28108553a67062344': 21,
 '0008d4175965bad7a17a7a662ca38e9e': 22,
 '0009469f3a744eb8b32418d4e45cc0be': 23,
 '000946ef4c43c478afe75f682efc5f25': 24,
 '0009a1eb67db223011afc8f43fc106d5': 25,
 '0009b41becd59653c6af5be8c45576f8': 26,
 '0009b570863eadea7403533c1294a051': 27,
 '000a7a57e2cd06b62b1049737b66a0ce': 28,
 '000b2aae95084c36d6ad5dbbdce94a78': 29,
 '000becc0dbc0e38980ed82ef5e34e802': 30,
 '000c14b56e2e54f381c1aa83fb7c905c': 31,
 '000c53ad7daa9b262a67770e0d0baba2': 32,
 '000cb6554c05a86f5792fb15f83bc80e': 33,
 '000ce9217de560cb8f6be185f6171d9f': 34,
 '000e25102a922421fcc3f0e0a2a57a18': 35,
 '000e8052831490f730921107d7b1acb5': 36,
 '000eea166a4ecb2cddd0b3baad9ce80e': 37,
 '000efcf14e96fcb2d889217e48883bdf': 38,
 '000f7ae0860ea2844c1949f7beee315d': 39,
 '000f92b03436b95b194db2919181e231': 40,
 '000f9a27be1bd4c0cb5847d4273792cc': 41,
 '000fc29b5b443dcda80a042c312441ae': 42,
 '0010b68a2f058e7987b6fe4c1af84f90': 43,
 '0010f16f7b14d6346b8ec84092312455': 44,
 '001130a1aaef226c4249aa77a4daa243': 45,
 '00119ae3513ec9772ccd9bd43bbe434c': 46,
 '0011c30ccd7735a396ca6ebba1faeaf8': 47,
 '0012a85f1df6f094249993eb1fe5824c': 48,
 '0012cc6c9c1cb7611cabc2a1421664e9': 49,
 '0012fe32eaefe1dccd53e7155ebc4a54': 50,
 '00131369083473219d7a993024a5c1b5': 51,
 '0014509c1b7032bd9ea24d86a421674d': 52,
 '00146534c152d20ce441ce8416f3e510': 53,
 '001480ca04a26759101bf4786f7a7658': 54,
 '0014918a15998271be68237e96b3907e': 55,
 '0014ce4986eaa25b4f0b5301415b7bb6': 56,
 '00159e48ca9758a3d9dd13399b18ca6b': 57,
 '0015f5e23ccfde0704bd725fddf98bd7': 58,
 '0016a60d7ab9624d01c7b324fa207a92': 59,
 '00171f1357a977b3c24770cf75818a25': 60,
 '001729c919a4ede57a06277e4796b7c8': 61,
 '0017b135946eccbb4d20379d5cdc810b': 62,
 '001815448e30f2227c1c3730c56cc49a': 63,
 '00182efa2de71166e66a86c26e74e914': 64,
 '00189ddfa1cbb293a8e95229271b20cb': 65,
 '0018a13f1cf075e53e723d7e9062dd64': 66,
 '0018b0bf106a0bc3da4d8d96645311ed': 67,
 '0018f262feaad408a13b9a9a4566a6a2': 68,
 '001969c4a2b926c1104e0585bec04e4a': 69,
 '0019eba4314f94f1f975ddc233947863': 70,
 '001a5b71e0f7259ba1ab8bad5bccc34e': 71,
 '001b0947d167e5653a59c72aa1e98184': 72,
 '001b2efb1ec53204af88c3f11acf2d32': 73,
 '001b6375384c0c0879cab67f93c59012': 74,
 '001ba858c1e8b8120f05199add8f67e3': 75,
 '001bcc23c5c015fd856d7aaa0d4c2293': 76,
 '001be38bc8826b59c307e745a6b655f9': 77,
 '001be57f3aa9d4527d12c979dfd81d36': 78,
 '001bebab9d4da0b434de8d6acb518d54': 79,
 '001c75f70c67358a9c7c892830fb2c1d': 80,
 '001cefbd71fca95c816f098a027f543c': 81,
 '001d148c03fa8fde62c002060a53d3a8': 82,
 '001d9c401c16ca13d2495dfd1c85ab58': 83,
 '001da7f9fa7fae385dbea6587205cbdb': 84,
 '001e45b19f975f21eb3f41b061af23de': 85,
 '001e4bd27c00ff1922ca47b693007fcb': 86,
 '001eb821e09ffd5971930d1b284ee9ac': 87,
 '001f1bfac2f32d723b8b933f37204aaa': 88,
 '001f66f5c8440fce34ce547867c3111d': 89,
 '001f6a136fb46e3fca6f7fd6c93a11b0': 90,
 '001fb4e8c8ecc42728bd62e2142caeff': 91,
 '001fed3bf1d49ad577f06a4aeda426cd': 92,
 '00200c808b10566eec52e7ec30005816': 93,
 '002012ecaa8ff800ab6ee93ecdc0c6bd': 94,
 '0020a75f9f33568bea105fea86c4347c': 95,
 '0020b948fad1830c16ed36e2f9a01a80': 96,
 '00213daea76e59e192d65965ea3db6fa': 97,
 '002142aa84b9be8a1757fe674a1e1067': 98,
 '002146880e50ba23ab20cf1e9e33c9bb': 99,
 '002193ed9267dca73527ab6bb27a06f3': 100,
 '00225b854ecc0ecf2fc3415ac70021b8': 101,
 '002278ef447327722d8a49ddaad18c89': 102,
 '0022c21c4d11afe7f5b617d15ffcdd66': 103,
 '0022de92eb05e31b163cd21fd15c6e0e': 104,
 '0022f19c8ca765a8b86d4ce140dbd0cd': 105,
 '00233488cc4fbb18e3f0404547463af6': 106,
 '00236ceff7f42b646e323ed312060987': 107,
 '0023cb02c0bd78760967facb9089a25a': 108,
 '0023d7ec017eac5dbb40c4837382583c': 109,
 '0023e008274c746fb24734cf2e730a87': 110,
 '002414e94fac8c1d0726d53a853054c1': 111,
 '00241ea340310f20e3cd5c82a3511df4': 112,
 '002453fa0d05ce27324f72b5a3757156': 113,
 '00247d6e908888b23caec175dc71720a': 114,
 '0024c9c1a33a112bb7670ca81f8dbd82': 115,
 '0024d027b79e61e632eb0915f830709d': 116,
 '0024e03c6cb8dc966e62a86195e07b18': 117,
 '0024fed207155504313fdbe62067d769': 118,
 '0025149632772473ae03b78044e71307': 119,
 '002556e9c0f02009c1304f0f2ab88320': 120,
 '0025dcb7deda75a86cf5ec0a5da676e7': 121,
 '0025f1a615fede6beccaf55f150e181b': 122,
 '0026238dd00b6c48fec06836e4e0c26c': 123,
 '00263ac47bdfe0e16696e49b874ea3fc': 124,
 '0026443b4682e57cb2087c6b46d15c82': 125,
 '00265e82acbfa394d3449034b065a02a': 126,
 '0026a8aa11bbd0151a44bbf1969b60ae': 127,
 '00274924395aa22c17f9d0077fc013b0': 128,
 '002781c0155eca0be2606ae732b5ba64': 129,
 '0027b1b4819468ef10d1f450c17bf987': 130,
 '0027ed36d7e82e527712f8bc533e21fd': 131,
 '0028fca1ce1233f1d0c60fe2c54d4466': 132,
 '00293b021096b29336560e1906f3d23a': 133,
 '0029b4bab40414753f02fb07a7fdef6b': 134,
 '002ab4a57179c8d68143b6f139b30bf5': 135,
 '002ae2c0872aa93d93541e64a0de9904': 136,
 '002b8b0ab168a1690e86efee89efb476': 137,
 '002b96b13d75b2461b2ef64d6eab5900': 138,
 '002ba431ffee32998a59aea637820b0c': 139,
 '002bdaf8d733f36373dc041bf1ee7c45': 140,
 '002c8360d7585d902fc66749251a1b7b': 141,
 '002cd8833d3b7781122abe8dcb9d47cb': 142,
 '002dc6661677ed3eb3807db229f49aac': 143,
 '002e844a6db1f7bf5d3fa170d4960b9e': 144,
 '002fd1eb9a39080b433142f27088323a': 145,
 '002fef91b06a176a406292c9fab4d6b5': 146,
 '003018755b0f99cab62136eccd2d3b24': 147,
 '00306cdd0fa9de61ce9573b769a90ce2': 148,
 '0030cb0d5cd5ee34243137ce697cffdb': 149,
 '0030e4a6f045ff8057c8d8bc6827766c': 150,
 '003122605060b084d598b01e65f1cb69': 151,
 '0031e6f4b8ce567e9d430943e3f39d3f': 152,
 '0032213ccfb69585755843fef5c2ec9f': 153,
 '0032bda0ed1f0a5f4bbeb57f6486a3c2': 154,
 '00335b10867c76a4e04d280e6f867502': 155,
 '00337560b7390c0313c5c773821fc9d9': 156,
 '0033879948720e921a6c8cffa634a704': 157,
 '0033e4c39e663db608bae8d047cab0de': 158,
 '00341d1d0ed7b202f4127eab7c630118': 159,
 '00342a0a1dc890fa916b73f3f0fc4c2e': 160,
 '0034a9da22c74b941ed09308ce00b323': 161,
 '00350f0f5f39faf4062eac4535029681': 162,
 '0035233e8da6d1c2161ef4eb327d9ba5': 163,
 '0035275cc2c752411da42daff839b51d': 164,
 '0035b22e417b13a8442743e17a1d2e9a': 165,
 '00362f1429659da415423f06ce74cf33': 166,
 '003641d937eedac6fce0904437e22876': 167,
 '0036d079fc389ba68b15371bc54fe8dc': 168,
 '0037009715d0295faca8d7887bb5b352': 169,
 '00378ee5978b7d7e4c2da60907c60561': 170,
 '003886eb288afbaf824fc70e675bc13e': 171,
 '00395a3044de752648aa07b7c59ed692': 172,
 '0039d9068a038ce4e41044614ac73a83': 173,
 '003a2de082cdb649f0e09190b532d1ae': 174,
 '003ad410346aa7441ad641996e4a0c2c': 175,
 '003b26153314621486065eb8b11f6c09': 176,
 '003b5ccc2532c790a0808fe8f471d096': 177,
 '003bc4a108b79d8cf3cc2e5158259b0a': 178,
 '003c4c426ce9f2bf35a226fa72b5239e': 179,
 '003ce421dac565f396a2eaa72a0d9ae4': 180,
 '003d097e2e37edb301d57bc5b50feecf': 181,
 '003d6891f246bb3e298f07d821e1d251': 182,
 '003d6f89bf7ec5851b8060344d3a9ec1': 183,
 '003d703823b0823f1b8a3f87835e9ec5': 184,
 '003dd4986ffe826b07dca87da9006607': 185,
 '003dd629c36d22cda695bdf2fdc8fa49': 186,
 '003df6726ebdba97c7efc6d3b58aa496': 187,
 '003e03a041589ff414355958191f948a': 188,
 '003e23e42f9e165f15c34b6f1c9b5dbf': 189,
 '003e46c3d5128aafaf2adefa1d6619ac': 190,
 '003eca464cc71ce0c940b891086b03e7': 191,
 '003ee91bd42e11da9063d6b4018c4261': 192,
 '003eef14cbf245679782bd03b7055bcd': 193,
 '003f47c62ecc91d26462ce2e9b7708eb': 194,
 '003f9ddc5626760044dbe75fd8f78bb7': 195,
 '004088c0f34226afa9dd495172cb550d': 196,
 '00409c8126dda8344ec7506e4b4c8d90': 197,
 '0040d04b4fcd6177bbfe55e60282d098': 198,
 '004110f29f096b5fb8fca6eea0b149a7': 199,
 '00415091c8880c7828654598b57c70f8': 200,
 '00418c3b93a27217d860ec5891d0215a': 201,
 '004199d0c49ba5c8e80271ddbc55b74b': 202,
 '0041cfa1f91d52725c11bc5b2df4c1d7': 203,
 '004229279328a3dc942232c42d86f2f0': 204,
 '0042cf7ca4c9ce24968ddfda7cb2fcae': 205,
 '0042e425190d3c25161a904daf012cd3': 206,
 '004344be1d5a3aaaa1d9df174676d284': 207,
 '0043b939f14c13f5f2f70079afdbed8d': 208,
 '004505a6b64f97c8af448de2cf93e1a9': 209,
 '00458264eeddfc37e91b760003b12147': 210,
 '0046e050357ce9f3e211d42678e61d97': 211,
 '0047181a94022434140fd22ed16adbee': 212,
 '004748ae953afe922d002008e4064e79': 213,
 '00474a239e9a0f0bdc30a1b23188625a': 214,
 '00475d185c49240a0891e56746976281': 215,
 '0047d21cd07bd889f1fa5caffe6dd374': 216,
 '0047ec0df517dfe9ae58934de15f1099': 217,
 '00481797e88d9dc90138c668d29be8fc': 218,
 '0048766e18139bdc3de6ffda320a840e': 219,
 '004894c67a74c09a143677432d3b7c86': 220,
 '0048d58704d34a5b5cfe9c9c663a27b4': 221,
 '0048df266274dda0103f9aefd0cf1df2': 222,
 '004917a09092509e85352266ccbb1149': 223,
 '00492385a51dfa22298b4aad57e341da': 224,
 '00497c6757e92d8ff1ca53e0ece9d809': 225,
 '004996c344d3e18c5f6e605ad8471fc6': 226,
 '0049e49fdd4563fab2851310edd9d064': 227,
 '004ab2825cd0012955fa4f48c63407c2': 228,
 '004b99df6baeec976b8f5d1cae8c27bd': 229,
 '004c18536aeac91e102517fe07e84caf': 230,
 '004cc96b6901ba4886eb046bc6c1c7c5': 231,
 '004d057ab5b0635b97a59cc0b895c778': 232,
 '004d3f9105568c089177bf0c3a1023e4': 233,
 '004d51a502ff2e3e32ff18544796fd29': 234,
 '004d923531efd7ae5547757a56ff8ceb': 235,
 '004eec90ee4f6822847c8f16574e5222': 236,
 '004efe959e3170b24aa585c63849b29e': 237,
 '004f357ac13ce5d06cd7ffa4355b06ef': 238,
 '004f9b10b755b7c35bb64da0549f83a0': 239,
 '0050631f71251261288393b56db4cbd7': 240,
 '0051ccfa6d7bcf5b943564c627978b59': 241,
 '0051eab3d36d09c9f5b83dcda0b91b63': 242,
 '005236592864e3830efdf80e2f3d251e': 243,
 '0052f538f5e79c99cb1a6fc74f95d6d0': 244,
 '005315a0117e6a09702519cccf0143d7': 245,
 '00533a9973d886cff27537a392fcab0f': 246,
 '005341ad398a52a6f018db0902bcaf03': 247,
 '00537ff73e0c630439396862a5d18b6f': 248,
 '00538a8adaf88a892c0cc10a43a34455': 249,
 '005482aee31f89f5e65e7f9336b67ec1': 250,
 '0054d56a5315e67cd2a293f48564b7d9': 251,
 '00559958f09754a9a914602a2d7885f9': 252,
 '0055d5db97d46433f36245eaea85087b': 253,
 '005602d6cea2ee42349ab45d75c4dfbf': 254,
 '0056887febbebfbb1e82f445c6d54417': 255,
 '0057bc661d281dd2d7fd091ff4b6c2a8': 256,
 '005826a88d069c6a169c81dc24aaf6c4': 257,
 '00585127d2935de167c06a1d4e993095': 258,
 '0058644f6ce833705b906c1fef4741a1': 259,
 '00586bed86290e760ff382de28a5d364': 260,
 '00587dbc44994ca4d17829f47439460c': 261,
 '00588de3bd4bcc5f56c9a60d6091b212': 262,
 '0058a2c5f78b1552db5ec28089f41768': 263,
 '005912fdc3fafc8759ca22195c05acad': 264,
 '00595c833f8dcc573fe97cdaeb7f928d': 265,
 '00597db2e60d25fa29bb878242c0bf40': 266,
 '0059f3d64595de97268aaf55238d036b': 267,
 '005a02861d37b914443908257d941024': 268,
 '005a24122a286da5422d2727f5bbcb7a': 269,
 '005a8ab14c765a66facf5c4f3764ea30': 270,
 '005b340a512610a1e232dd68b37634d1': 271,
 '005b45f8f68e3c704500b7c56ec994d3': 272,
 '005b688e24827769cefe0eeb732a10f1': 273,
 '005baecff7f069c0bcecca377dd7e621': 274,
 '005c4374d383fbc0216379a709f7da3f': 275,
 '005c6cf54e65c88c3f3f90b0544b864d': 276,
 '005ccd47f796f2fae4a073698fc2a165': 277,
 '005d0738c9277453697615ef6724045e': 278,
 '005de75543b3fc93621431cf18175d90': 279,
 '005ed5b0d111c55b6ca6a25634d7d162': 280,
 '005f2f88a65a1850e6d600e6f24f2da5': 281,
 '005f470e4ff6be8ebd115d8cd954eb51': 282,
 '005fb5edf7100ee903d74793d8e180c2': 283,
 '0060402b454e0d835f12aff93ad5fa63': 284,
 '006058327a4b435ed88290c4cde646d9': 285,
 '0060e2c9e2c6ff03faf1ce77156ba576': 286,
 '00615d571c6e2ede6428d57470dcd8fb': 287,
 '00619eaff2d0c15e729a3ffdcdd3c517': 288,
 '006247236b2f8a2f48f1d5111baeef50': 289,
 '00625e0f1985ae7f3c0a6b028b760491': 290,
 '006278ad5869b4b202897c33c2b47d36': 291,
 '0062a4850106b95ec67e63a87a6c1e11': 292,
 '0062ab2f3bccea0a3132d332a17c149e': 293,
 '00631d2c4aacfb324f1d206c8ccbd40e': 294,
 '00635bbefa32ce14169e89bbada982d8': 295,
 '00636e5414474e1bba2036fe68e33ad8': 296,
 '00643c7f3ecea8f09611a1ca7b3c25c9': 297,
 '00644258d87941354e96fd53418c7bcb': 298,
 '00644d451ae8750d7304570fe3041705': 299,
 '006539395d2b1591ba9d7d38ae0b09fa': 300,
 '006624444f0db10dde89f02423007711': 301,
 '006641ceeb2021ab18aad3473c547530': 302,
 '00666887f899f45976d1ee92636c0ebf': 303,
 '0067871f2ccf4cc941ef0c9b21c78ef9': 304,
 '0067d8c9eb0ed83b0391510efde4e425': 305,
 '006801cae82a7707caeaae6408bd2f12': 306,
 '0068d5affa55bead5f77ea9414ce74e2': 307,
 '0068df7f839e2ea0646c1e950941f183': 308,
 '006907653299d4c25928cc5404e79d82': 309,
 '0069767960a1582aedf35c21b0c3c9ee': 310,
 '0069a9e398d7dfb61857bea24f808cc6': 311,
 '006a9455407fa32bac94067babcf6016': 312,
 '006ac3fb6887d5af8629f4e87c4926d7': 313,
 '006b32ba388a5476f44616f8dec68acd': 314,
 '006c7bf89572e34a71f138d033470b64': 315,
 '006ca9f72e150f3562f6b3e85b5c6e3b': 316,
 '006cbfaeec7c860700cbe5996d43dcff': 317,
 '006cd1a70db2cf6e1317a6f1196e8087': 318,
 '006d03ecad0f9e22b3291271f96c85f9': 319,
 '006d57d6a12b82683555c35ed51c046b': 320,
 '006d8736fbb7ea107086e7318ccbc6b6': 321,
 '006d93d689136c64e8e150d749f30674': 322,
 '006dfecc4b6e40cd7b333ed1ad000c5a': 323,
 '006e6d1e142f72b904e74936af5e6291': 324,
 '006f093466e99ec060d53a6f3eb49382': 325,
 '006f45c628993702c71f6794cff17b22': 326,
 '0070735f6ca46c08ba3051b43f74311b': 327,
 '0070a3167eb2684ee9ac6e6df8a997ab': 328,
 '0071be319b49871916ffbc66d73593d1': 329,
 '00720113b6c451f34192d3abab63df5b': 330,
 '00721a2adb4b19accfa6577b457901a3': 331,
 '0072626e63f4384995b56b35e8a30c19': 332,
 '0072aa53cc6aad929c19212a9b49550e': 333,
 '007395a0312179188f8b12726f7e6bb7': 334,
 '007572195414be03e7a4dcfd7900fd52': 335,
 '0075a06d0d2fee236ec289b61d7c7f45': 336,
 '0075a47e1e3050515cad23f6fef3710c': 337,
 '0075f1b5ebf7e721c7f3d3d03409d07f': 338,
 '0075f9e7be832abac29433d7a6223cce': 339,
 '00766004e7d69b7e7c5e71f829e5bafc': 340,
 '007688ce4d6f38dfd13ea560f40d84a7': 341,
 '0076b818ee94c4ae1090cec23b14076f': 342,
 '0076b870e2c094ada0cfbc5644aada02': 343,
 '00770f750081702b060a2605c24a7267': 344,
 '007736ed9f957a703c3d51da4b5bd220': 345,
 '007766bdb47b7b071139c6806815185d': 346,
 '00776b696d108000b1db7dfbc612a1e9': 347,
 '00778458665da655e0b6823369c6fb82': 348,
 '0077928c75f02a28bb01818630eb0e96': 349,
 '0077b03c8ef3e9910e791c34a3a82dfe': 350,
 '007807f1613a78b486ee6a91474414ef': 351,
 '00780bfc4870e12012161693b33942c4': 352,
 '00781d7e36a1dcb7f9f3262a81e8456c': 353,
 '0078383b97f5daab98e67d539feb189b': 354,
 '00786451d1fe3fe2986a586c324c9ef8': 355,
 '007876c8a891d6210e2d5944320d73ed': 356,
 '00787bc63dfae484da7b57ea25de31ca': 357,
 '0079a29aa959397f56ea555755844002': 358,
 '0079df9d7c822830030383cf14420b2c': 359,
 '007aae77d2f042d0d54a04e54804e728': 360,
 '007bb524608ebaf9677a7f4eedf07ec6': 361,
 '007c0f559de10d515dcd9b5633b601b3': 362,
 '007c54b8687836bbfa906914ce008049': 363,
 '007cadefd25bba6e08b189ee6b4efda2': 364,
 '007d81f19d130b94c8486384e8ec2fc5': 365,
 '007d950318abb19ffb53f36c3f3584a0': 366,
 '007da63e4510b0af7d970b971700cd03': 367,
 '007de3a204a27210058b5bd67be16752': 368,
 '007dede1866ee66d1ae6774a65af0295': 369,
 '007dfba089ab6a7cbf0fd254e117928f': 370,
 '007fbaeeb3b11a0925f9fe31390234e1': 371,
 '007fc24f024283cd46455f66e0c6a134': 372,
 '00800ca8255a8f33976b9dfc81f23a29': 373,
 '0080900ccb6700f0443b54284aba4857': 374,
 '0080db56ec0d97a73cf43999c43615e4': 375,
 '00812aa30b97a76efa188bc8e140fd9b': 376,
 '008161f2ab3624817891905ed307ad5d': 377,
 '0081956bbb3b55534804d8b73693162a': 378,
 '0082794b7dc6b5b38a1d841c39811098': 379,
 '00828a3136b95db20d2d3e641ce543a7': 380,
 '0082efee0b4e809156c4a3c474c411c2': 381,
 '0082f9ddfe93131c44bf0cd8035c970c': 382,
 '0083247a6f96c0fbb9a9ff2c4b9b0fa3': 383,
 '0083441b54e832bcca001c4839192a2d': 384,
 '00834bad602d81d6ef4f3eabff996bde': 385,
 '0083fcf2ad35000cad54b3afd14b0fc8': 386,
 '0084cd1c5c1ceb34b848f8826c9a63ea': 387,
 '00854cfce349f10f7bb5c076a1c073cd': 388,
 '00858792b2a1aab4695e6aeaa2ecafae': 389,
 '0085b97f46e676be08c02f3938680133': 390,
 '0085eeb44a2f0fdbcdfb6f1b01e804d9': 391,
 '0085f88ba6e5db7608d1f6b9b9f819b4': 392,
 '0086208d0d24a73475294f84e5f20482': 393,
 '0086fff105c9a147757e549e2eb63a92': 394,
 '008739c85f10243be10c2b3f24686575': 395,
 '00873a42c7948a16fa0d52c550a6a851': 396,
 '00876f613b1895dd51e067c8fab25c88': 397,
 '0087fceea365d0f0502df194c284cb96': 398,
 '0088701735064018ddad9eb3954946e6': 399,
 '008983dae9bd91712057dd64c9a3ac5f': 400,
 '0089f64780d35bf7038b363b763899e1': 401,
 '008a10a618c3c5f3c4dd91dcdbd88600': 402,
 '008a187377a0bb4af427cf5eea5f6ea5': 403,
 '008a950a0c0654e4f991bca98baef647': 404,
 '008a966dff0c919f02ec3c23f181b57d': 405,
 '008b231fec52aa620bd269b71d59b25c': 406,
 '008babc431046f40ff8e4831841976dd': 407,
 '008bec799a050ff594afe2f2ed84c8b0': 408,
 '008bfffc4edbaf555e963daa5596dbdd': 409,
 '008c0e444b0cad3ac9d9309696851171': 410,
 '008c15d52bf1b3898338d019233b3813': 411,
 '008c95460c9c3e146503a1ab83ee4e6e': 412,
 '008d9bac0e805dceece54d2fa637b7fd': 413,
 '008dbea7316710c9eec4ed5842b99b06': 414,
 '008e90560d196fc4d30497bd5954e912': 415,
 '008ed27d8ab87f0cb5377fe2e4121663': 416,
 '008fc75037acf2c6793588b8459f850b': 417,
 '008fcc0f01edfa16bae702869a01e2a8': 418,
 '008fe36b370e744a21b75a24ccc3c7f2': 419,
 '0090169bacf7cfff44db906e1e133454': 420,
 '0091ae97e27b73ad9b7a71ad470e0935': 421,
 '009210aef8ff15cfb60468c681592828': 422,
 '009335938967d68bf5e3a9c2d481cf91': 423,
 '00933cd07b03c0c55b0c14cf833bcdaf': 424,
 '00948cb8c21cb17ba186f7fa24cff04a': 425,
 '00948dc1777cb3e406367b6ef84aee4f': 426,
 '009503b8c0b3d18552ca0602cce732da': 427,
 '0095c6e8c9ac72b9fc37d016defcb067': 428,
 '0095fd77cd748e9e615a1f8359d97da1': 429,
 '00960a2c69cfa63fbe14113d87bf469d': 430,
 '009623752e16ce9be5e2e70c66ae6a7a': 431,
 '009629f00977d3c7bf14ead282d0ea93': 432,
 '0096f60379c887ec5d01376f575f3099': 433,
 '009753fd39d85656f170758f23516ecc': 434,
 '00978093f674e3e366226bd0dc7ff1e0': 435,
 '0097ca2cc17fdb8c40a2edc6af78bacb': 436,
 '0097e77a6f612a6487b6b2b0a54ddcb8': 437,
 '0099d1a70b2c1cf5248e90537bf11a25': 438,
 '009a652783f52d71f08dbd426f0386ec': 439,
 '009a6ba1b697aa26ab251b492ddacca5': 440,
 '009a7b0b02291e801d862c70888a0b60': 441,
 '009ade8a0a7c3799be159c3008335639': 442,
 '009ae335d08f352e1981a6b7f938024c': 443,
 '009b3ef84127885139e9512eefd8b017': 444,
 '009b4272e77d0b9c365c6a7ecba5a10f': 445,
 '009c1ff8248feea46080c7e84d9782d7': 446,
 '009cc71ef50407f4090e7d0d1b878033': 447,
 '009cff78e1bea312a5e6363d8a2cbc49': 448,
 '009d103074c7e9789642f7e0c5e384cd': 449,
 '009e37defe9b536dcaf5ea7def2408e5': 450,
 '009e4c5247b9793b2efcf332c31c1d6e': 451,
 '009e8217ee17ecc4600eb7b39d032711': 452,
 '009eab2097aa50e972ae1883660b6db6': 453,
 '009f3f289d3bbd3028783c80e2265226': 454,
 '009fe5dc60d6532682275751cd8926b6': 455,
 '00a0f9fcb4b57447a6ab2edc681a1169': 456,
 '00a2084daf225268a132b040578414c3': 457,
 '00a21c21c8ece81b580f118dd8eac60a': 458,
 '00a22805ec72a61d917fd3596af0c5c8': 459,
 '00a25762bf3bff46a6f674595ce321fa': 460,
 '00a27bc6cd3e45cee8b99416d219b8d8': 461,
 '00a2e0e4b87f2d72969421882f1b7a2f': 462,
 '00a335269ad60a766e121cf262eb5512': 463,
 '00a34ca93e3ea71b5f5d3b545056a769': 464,
 '00a38909f2c131628181019045d6e476': 465,
 '00a3aa0b8370ddf108c61d3c1d2cf9df': 466,
 '00a3dff70aed7da0dedf8acbe249e176': 467,
 '00a413cd1c2cc61adefd11d1dc61d490': 468,
 '00a43972028fefa8e1347148e1bbe332': 469,
 '00a44ab813f03c7f6cde2615916f75ff': 470,
 '00a4cc421bc99a2c789776a72e498e49': 471,
 '00a4f084b105faa7d4d4dd67954a0dcc': 472,
 '00a577c60f64ddacac8049de1d8bd49a': 473,
 '00a68ddbe69586f4d0105a41b6e5d6bd': 474,
 '00a697aa8f642b541d773514f8c73005': 475,
 '00a708b2c42ae0d98b402efa80d0aa6c': 476,
 '00a74d6c1fe8b758060bd84bd6b9c7ec': 477,

In [32]:
user_id_dict.get('0002eabd63d3cde55b2c77f2dcaa6ce0')

2

In [21]:
# Get recommendations for the a single user
userid = 12345
ids, scores = model.recommend(userid, sparse_user_item[userid], N=10, filter_already_liked_items=False)

In [22]:
ids, scores

(array([  748, 24685, 25728,   618, 31676, 20165, 26469, 11180, 20098,
        24043], dtype=int32),
 array([1.0415375 , 0.93676543, 0.6259685 , 0.5555456 , 0.52751076,
        0.51951224, 0.47814673, 0.46559575, 0.42275968, 0.40004197],
       dtype=float32))

In [24]:
for id in ids:
    print(f"id is : {id}")
    article_id = data.article.loc[data.article_id == id].iloc[0]
    print(f"article_id is : {article_id}")
    article_url = pre.article_df.url.loc[pre.article_df.article_id == article_id].iloc[0]
    print(f"article_url is : {article_url}")
    print(article_url)

id is : 748
article_id is : 0CzbYaKU_rjkm9ddwIr3Xehls7k4a6ohdB2sgkvQMLg
article_url is : https://www.ratopati.com/story/151779
https://www.ratopati.com/story/151779
id is : 24685
article_id is : dhsWwaBXwHxX3ORdRK3w1PehCFc5lC3U3RMGpgLf6Tk
article_url is : https://www.ratopati.com/story/149970
https://www.ratopati.com/story/149970
id is : 25728
article_id is : fMrzWpiWyYm4JKSJvHSwGQRDybfB_HauC_eCvXilYrg
article_url is : https://www.ratopati.com/story/141729
https://www.ratopati.com/story/141729
id is : 618
article_id is : -yuYUjmARhuYM0XPZzCkSCA0KN5T9m9FU0_peb_Uemk
article_url is : https://www.ratopati.com/story/142715
https://www.ratopati.com/story/142715
id is : 31676
article_id is : pM2UeEnAa_74tgSz8hAtq2o_n3_iV0R52g36m4MaOMw
article_url is : https://www.ratopati.com/story/150087
https://www.ratopati.com/story/150087
id is : 20165
article_id is : XAo-LBYnPGOft-Cw8FqmT0x1ABNachyKp5PJDffOkdI
article_url is : https://www.ratopati.com/story/153880
https://www.ratopati.com/story/153880
id is : 26469
article_id is : gZqrQK6CbM6MmoJ8XWWFD5fpBhv2OrrN6eNFcFzRYFg
article_url is : https://www.ratopati.com/story/149237
https://www.ratopati.com/story/149237
id is : 11180
article_id is : Hr3snl0rSye8e2Pp2vCAB23fb8GVaFLMvGAPKSNzHrE
article_url is : https://www.ratopati.com/story/141697
https://www.ratopati.com/story/141697
id is : 20098
article_id is : X4bwnYn1nHYoviIH3_MnRnwy0t3PfR8rfUYmggBpcm0
article_url is : https://www.ratopati.com/story/150703
https://www.ratopati.com/story/150703
id is : 24043
article_id is : cZ0uOVCrMw_1BKqUmf93E_B18K0S6EEVhFOG4inxeJs
article_url is : https://www.ratopati.com/story/151016
https://www.ratopati.com/story/151016

In [33]:
article_list = [pre.article_df.url.loc[pre.article_df.article_id == data.article.loc[data.article_id == id].iloc[0]].iloc[0] for id in ids]

In [34]:
article_list

['https://www.ratopati.com/story/100002',
 'https://www.ratopati.com/story/99687',
 'https://www.ratopati.com/story/107586',
 'https://www.ratopati.com/story/99658',
 'https://www.ratopati.com/story/109291',
 'https://www.ratopati.com/story/96483',
 'https://www.ratopati.com/story/99363',
 'https://www.ratopati.com/story/97844',
 'https://www.ratopati.com/story/99308',
 'https://www.ratopati.com/story/116201']

In [25]:
# get related items for the beatles (itemid = 25512)
ids, scores= model.similar_items(5555)

# display the results using pandas for nicer formatting
# pd.DataFrame({"artist": artists[ids], "score": scores})

In [27]:
ids, scores

(array([32163,  5555, 19827,  4157, 12444, 11860,  7642, 16884, 32752,
         2286], dtype=int32),
 array([0.99999994, 0.99999994, 0.9999998 , 0.99999785, 0.99999434,
        0.99994934, 0.9924626 , 0.9910785 , 0.99055636, 0.9739194 ],
       dtype=float32))

In [26]:
for id in ids:
    print(f"id is : {id}")
    article_id = data.article.loc[data.article_id == id].iloc[0]
    print(f"article_id is : {article_id}")
    article_url = pre.article_df.url.loc[pre.article_df.article_id == article_id].iloc[0]
    print(f"article_url is : {article_url}")
    print(article_url)

id is : 32163
article_id is : q8ezYzI-6lm9PLFAG5qAgsyKqgCJTR1yWOa07QPYaJ8
article_url is : https://www.ratopati.com/story/100002
https://www.ratopati.com/story/100002
id is : 5555
article_id is : 8N-b4NU6ctSt19zPRASQIwqjO7cwuqt0-EgB0ZsodI4
article_url is : https://www.ratopati.com/story/99687
https://www.ratopati.com/story/99687
id is : 19827
article_id is : Wd8uhu5FR1Ww7_0PeA3r536olVJsG_9Gn1GejsYK-_s
article_url is : https://www.ratopati.com/story/107586
https://www.ratopati.com/story/107586
id is : 4157
article_id is : 5zefPW4RKW1d7YAYIFcuzEOru89C2VVny1YcxLhRYnY
article_url is : https://www.ratopati.com/story/99658
https://www.ratopati.com/story/99658
id is : 12444
article_id is : JzrtafoOkcTVcU17BOcjHJg1pG0rM1u9FB3Ud4GxAco
article_url is : https://www.ratopati.com/story/109291
https://www.ratopati.com/story/109291
id is : 11860
article_id is : J1VCGQom78fsbQlhY2SCKqgGybWIzXiijYAalamGPh0
article_url is : https://www.ratopati.com/story/96483
https://www.ratopati.com/story/96483
id is : 7642
article_id is : BsKQ3D847guCwEr_JYbKAMRBVvxMSOqOkIWBW8dv53s
article_url is : https://www.ratopati.com/story/99363
https://www.ratopati.com/story/99363
id is : 16884
article_id is : RWM17i2dsYLAkvPRFps_R0qqs0k-9qwC_RVuQS_BkKo
article_url is : https://www.ratopati.com/story/97844
https://www.ratopati.com/story/97844
id is : 32752
article_id is : r85BLWWoVXbx3TUftcMGaan0WjJrqxhX2VPz2qaFxzw
article_url is : https://www.ratopati.com/story/99308
https://www.ratopati.com/story/99308
id is : 2286
article_id is : 2nn6Xpswz0Zd6Yj5lSJhxAPUTDp59WLLVpIaX3RxPvs
article_url is : https://www.ratopati.com/story/116201
https://www.ratopati.com/story/116201